# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'

Options:
 cmake-options: '-DBUILD_GUI=ON -DBUILD_TESTS=ON'
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
